### ISSUE TITLE
Event List: Not listing workflows

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#219]
### Problem description

I'm 100% sure that worked before. I have created this workflow and nothing shows in the list of workflows waiting for events:

```
description: A simple 'action' state that sends a get request
functions:
- id: get
  image: direktiv/request:v1
  type: reusable
states:
- id: getter 
  type: action
  action:
    function: get
    input: 
      method: "GET"
      url: "https://jsonplaceholder.typicode.com/todos/1"
  transition: wait-for-booking
- id: wait-for-booking
  type: consumeEvent
  event:
    type: guestbooking
    context:
      source: 'bookings.*'
      customerId: jq(.customerId)
      venue: Sydney
  timeout: PT1H
  transform: jq(.customer)
```
