### ISSUE TITLE
Cancel crashes

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#220]
### Problem description

Running this workflow and cancel it, crashes the UI

```
description: A simple 'action' state that sends a get request
functions:
- id: get
  image: direktiv/request:v1
  type: reusable
states:
- id: getter 
  type: action
  action:
    function: get
    input: 
      method: "GET"
      url: "https://jsonplaceholder.typicode.com/todos/1"
  transition: wait-for-booking
- id: wait-for-booking
  type: consumeEvent
  event:
    type: guestbooking
    context:
      source: 'bookings.*'
      customerId: jq(.customerId)
      venue: Sydney
  timeout: PT1H
  transform: jq(.customer)
```

![cancel](https://user-images.githubusercontent.com/10879611/150466746-2ea51a8c-7be3-4eda-8ba3-769dea56a614.png)
