### ISSUE TITLE
Workflow Instance: Logs horizontal scrolling not working

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#231]
### Problem description

If logs exceed the width of the log output window, there is no way to scroll horizontally. The same issue exists in the full-screen mode of the logs. 

![logs1](https://user-images.githubusercontent.com/10879611/150661144-ee0f9579-ad22-4ab0-a325-6ff4f037ffd9.png)

**Comment by porleaaron** [comment]
Please let me know how I can reproduce this bug, I did try but not found how to reproduce this

**Comment by jensg-st** [comment]
Example Workflow:

```
states:
- id: hello
  type: noop
  log: "helloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldhelloworldTHISISTHEEND"
```
